# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reicast
email: team@reicast.com
description: >
  Reicast is a portable dreamcast emulator
baseurl: ""
url: "http://reicast.com"
github_username:  reicast
facebook_username: reicastdc
twitter_username: reicastdc


# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
